name: rustfmt

on:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.*"
  push:
    branches:
      - main

defaults:
  run:
    working-directory: rustfmt

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - run: cargo test --locked
      - run: rustup component add rustfmt
      - run: cargo build
      - run: cargo test --release
      - run: cargo fmt --all -- --check
