name: Rust

on:
  pull_request:
    branches: [main]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          profile: minimal
      - name: Add rustfmt
        run: rustup component add rustfmt
      - name: Build
        run: cargo build --verbose
      - name: Run rustfmt
        run: cargo fmt --all -- --check
